### PR TITLE
Adjust 65c02 STA abs,x behaviour.

### LINKED ISSUE #1211: Enhanced Apple IIe problem writing to disks
I am experiencing a problem with Clock Signal 23.10.29 where it writes to Apple II disks incorrectly when emulating an enhanced Apple IIe. Steps to reproduce:

1. Use [AppleCommander 1.9.0](https://github.com/AppleCommander/AppleCommander/releases/tag/1.9.0) to create a new blank DOS disk image:
    1. Launch the AppleCommander GUI.
    2. Click Create…
    3. Leave "DOS 3.3" selected and click Next >
    4. Enter a name for the disk and click Next >
    5. Leave "DOS ordered" selected and click Finish.
    6. Click Save.
    7. Choose where to save the disk and click Save.
2. Open the macOS version of Clock Signal and create a new *Enhanced IIe*.
3. Press Command-Shift-O and select the January 1983 Apple DOS 3.3 system master disk.
4. After it boots, press Command-Shift-O and select the blank disk created in step 1 above.
5. Type `CATALOG` and press <kbd>Return</kbd> and verify the catalog shows an empty disk.
6. Attempt to save the contents of the hires screen to disk with `BSAVE HIRES,A$2000,L$2000`. `I/O ERROR` occurs.
8. Try `CATALOG` again. `I/O ERROR` occurs.

The problem does not occur if in step 2 above I create an unenhanced Apple IIe instead. I cannot reproduce the problem in Open Emulator or Virtual ][ when emulating an enhanced IIe.

Bad enhanced IIe ROM file? Difference in the timing of 6502 and 65C02 instructions? Something else?

### PR DESCRIPTION
**Pull request by TomHarte**
Resolves #1211

Full list of required modifications:
- [x] STA abs, x
- [x] STA abs, y
- [x] STZ abs, x
- [x] ASL abs, x
- [x] LSL abs, x
- [x] ROL abs, x
- [x] ROR abs, x
- [x] DEC abs, x
- [x] INC abs, x

### CODE REVIEW

File: Processors/6502/Implementation/6502Storage.hpp [hunk 1]
```diff
@@ -73,14 +73,16 @@ class ProcessorStorage {
...
 			OperationCorrectAddressHigh,	// copies next_address_ to address_
 
-			// Implements 65c02-compatible version of CycleAddXToAddressLowRead specialised for STA; on that processor
-			// a non-page-crossing `STA abs, x` acts exactly like a 6502, doing a read of the target address before
-			// the write, but a page-crossing store instead performs throaway read from PC-1.
-			CycleAddXToAddressLowReadSTA,
+			// Calculates address_ + x and stores it to next_address; copies next_address.l back to address_.l.
+			//
+			//	6502: schedules a throwaway read from address_.
+			//	65C02: schedules a throaway read from PC-1 if a page boundary was crossed;
```
Comment (ryandesign) [inline Processors/6502/Implementation/6502Storage.hpp:82]: Typo here: "throaway", and typo in commit message: "Generalse"
